### ISSUE TITLE
python3.12

### ISSUE THREAD

**Issue by jowodo** [MicrobialDarkMatter/nanomotif#18]
I failed to install nanomotif in python3.12.  It works for python3 version 3.8-3.11 though. This is the output from pip install: 
```
Collecting nanomotif==0.1.18
  Using cached nanomotif-0.1.18-py3-none-any.whl.metadata (10 kB)
Collecting wheel (from nanomotif==0.1.18)
  Using cached wheel-0.42.0-py3-none-any.whl.metadata (2.2 kB)
Collecting requests (from nanomotif==0.1.18)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting numpy==1.24.4 (from nanomotif==0.1.18)
  Downloading numpy-1.24.4.tar.gz (10.9 MB)
     ________________________________________ 10.9/10.9 MB 51.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  _ Getting requirements to build wheel did not run successfully.
  _ exit code: 1
  __
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  _ Getting requirements to build wheel did not run successfully.
  _ exit code: 1
  __> [33 lines of output]
      Traceback (most recent call last):
        File "/home/apps/python3/3.12.2/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/apps/python3/3.12.2/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/apps/python3/3.12.2/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/home/apps/python3/3.12.2/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/apps/python3/3.12.2/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-yb125k0h/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-yb125k0h/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-yb125k0h/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

_ Getting requirements to build wheel did not run successfully.
_ exit code: 1
__> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: cannot continue installation due to an error. Please check the messages above.
```

Thanks

**Comment by SorenHeidelbach** [comment]
It currently does not work on python 3.12. This is because of the NumPy version. We will bump NumPy in a future version to remove this incompatibility.

Best Søren

**Comment by SorenHeidelbach** [comment]
It has now been fixed, with more slack version dependencies of NumPy (https://github.com/MicrobialDarkMatter/nanomotif/tree/v.0.1.19 )
